format = """
[](#60009e)\
$username\
$os\
[](bg:#00962e fg:#60009e)\
$directory\
[](fg:#00962e bg:#bf6e01)\
$git_branch\
$git_status\
[](fg:#bf6e01 bg:#0041b2)\
$python\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#0041b2 bg:#06969A)\
$sudo\
$docker_context\
[](fg:#06969A bg:#036A7A)\
$time\
[ ](fg:#036A7A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#60009e"
style_root = "bg:#ff5656"
format = '[$user ]($style)'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#60009e"
disabled = true # Disabled by default

[directory]
style = "bg:#00962e"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


[sudo]
style = "bg:#06969A"
symbol = "󱄼"
disabled = false
format = '[ $symbol ]($style)'

[python]
symbol = " "
style = "bg:#0041b2"
format = '[$symbol ($version) ($virtualenv) ]($style)'

[c]
symbol = " "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#bf6e01"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#bf6e01"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#0041b2"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#036A7A"
format = '[ ♥ $time ]($style)'
